name: CI

on: push

env:
  BINARY_NAME: simple-http-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch git tags
        run: git fetch --prune --unshallow --tags --progress
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - name: Install dependencies
        run: make install
      - name: Run lint check
        run: make lint
      - name: Run build
        run: make build-all
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BINARY_NAME }}-binaries
          path: build/

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download binaries artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BINARY_NAME }}-binaries
          path: build/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/*"
